# Docs: https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.0
info:
  title: vcluster-fs-syncer
  description: >
    Synchronizes `/var/lib/kubelet/pods` into predictable vcluster scoped paths
    at `/var/lib/loft/<vclusterName>/pods`
  x-cortex-type: service
  x-cortex-slack:
    channels:
      - name: dev-tooling-design
        notificationsEnabled: false
      - name: dev-tooling-support
        notificationsEnabled: false
      - name: dt-oncall
        notificationsEnabled: true
      - name: fnd-dt-alerts
        notificationsEnabled: true
  x-cortex-owners:
    - type: group
      name: fnd-dt
      provider: CORTEX
  x-cortex-tag: vcluster-fs-syncer
  x-cortex-git:
    github:
      repository: getoutreach/vcluster-fs-syncer
  x-cortex-oncall:
    pagerduty:
      id: P9HJAUT
      type: SERVICE
  x-cortex-dashboards:
  x-cortex-link:
    ## These are useful documentation links for this service. Please fill in the customLinks block if you have additional documentation links.
    ## name: The name of the link
    ## type: Choose one type from (dashboard,documentation,healthcheck,logs,metrics,runbook)
    ## url: The link url
    ## description(optional): Description to this link
    - name: Team PagerDuty
      type: incidents
      url: https://outreach.pagerduty.com/teams/PLP0Z2V
    - name: API Docs
      type: api_documentation
      url: https://engdocs.outreach.cloud/github.com/getoutreach/vcluster-fs-syncer#section-readme
    ## <<Stencil::Block(customLinks)>>
    ## <</Stencil::Block>>
  x-cortex-custom-metadata:
    app: vcluster-fs-syncer
    name: vcluster-fs-syncer
    repo: https://github.com/getoutreach/vcluster-fs-syncer
    tier: tier_2
    framework: stencil
    language: Golang
    stencil_version: v1.38.0
    golang_version: 1.22.0
    cli: false
    service: true
    product: Outreach
    lifecycle: in_development
    ## <<Stencil::Block(extraAliases)>>
    ## <</Stencil::Block>>
    reporting_team: fnd-dt
    lintroller: platinum
  x-cortex-groups:
    - lifecycle: in_development
    - tier: tier_2
    - product: Outreach
    - language: Golang
    - framework: stencil
    - type: service
    - engOrg: fnd
