name: vcluster-fs-syncer
arguments:
  reportingTeam: fnd-dt
  description: >
    Synchronizes `/var/lib/kubelet/pods` into predictable vcluster scoped paths
    at `/var/lib/loft/<vclusterName>/pods`
  lintroller: platinum
  oss: true
  service: true
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/devbase
    channel: main
  - name: github.com/getoutreach/stencil-circleci
