name: vcluster-fs-syncer
reportingTeam: ""
description: ""
oss: true
slack: ""
circleAPIKey: ""
lintroller: platinum
releaseType: ""
deployTo:
  environments:
    - staging
arguments:
  circleAPIKey: ""
  commands: []
  commitGuard: false
  datadogDashboards:
    custom: []
    mainLink: ""
  dependencies:
    optional: []
    required: []
  deployTo:
    environments:
      - staging
    serviceDomain: bento
  description: ""
  grpcClients: []
  kubernetes:
    groups: []
  lifecycle: ""
  lintroller: platinum
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  pagerDutyLink: ""
  releaseOptions:
    allowMajorVersions: null
    enablePrereleases: false
  reportingTeam: ""
  resources: {}
  service: true
  serviceActivities: []
  tier: 0
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-opslevel
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
