# syntax=docker/dockerfile:1.0-experimental
# This Dockerfile is used by Tilt currently. It should
# be kept in sync with the production one.
FROM gcr.io/outreach-docker/golang:1.15.2 as builder
FROM gcr.io/outreach-docker/alpine:3.12
WORKDIR "/app/bin"
ENTRYPOINT ["/app/bin/vcluster-fs-syncer"]

# Add timezone information.
COPY --from=builder /usr/local/go/lib/time/zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO=/zoneinfo.zip

###Block(afterBuild)
###EndBlock(afterBuild)

COPY ./bin/vcluster-fs-syncer /app/bin/vcluster-fs-syncer
